# ce8a2c04a7c3dfa90a0385212536417a
# Automatically generated by ResourceManager at: 2023-10-28 15:04:33.043569
# DO NOT EDIT THIS FILE MANUALLY. 
# If you want to regenerate this file, change the integrity hash in the first line to something else

# Some generic fixes
list = list[object]
dict = dict[object, object]

# Default import statement:

# Main content:
from typing import NamedTuple

root = NamedTuple("root", [
    ("hello", str),
])
