# d2965de707686693f9c02a2aa20835d6
# Automatically generated by ResourceManager at: 2023-10-28 16:23:27.369637
# DO NOT EDIT THIS FILE MANUALLY. 
# If you want to regenerate this file, change the integrity hash in the first line to something else

# Some generic fixes
list = list[object]
dict = dict[object, object]

# Default import statement:

import pygame

Surface = pygame.Surface

# Main content:
from typing import NamedTuple

root = NamedTuple("root", [
    ("bg_end_png", Surface),
    ("bg_test_png", Surface),
    ("hello", str),
])
