# 192c3aebbfdcde9b5c9f6c54752831ad
# Automatically generated by ResourceManager at: 2023-10-28 16:38:03.620345
# DO NOT EDIT THIS FILE MANUALLY. 
# If you want to regenerate this file, change the integrity hash in the first line to something else

# Some generic fixes
list = list[object]
dict = dict[object, object]

# Default import statement:

import pygame

Surface = pygame.Surface

# Main content:
from typing import NamedTuple

root = NamedTuple("root", [
    ("bg_end_png", Surface),
    ("bg_test_png", Surface),
    ("stick_explain_png", Surface),
    ("stick_stand_png", Surface),
    ("hello", str),
])
